#!/bin/bash

# Requirements #
# - maven command line (mvn) 

SCRIPTPATH=${PWD%%/scripts}/demo
TARGETPATH=${SCRIPTPATH}/target

mv clean -f ${SCRIPTPATH}/pom.xml
mvn package -f ${SCRIPTPATH}/pom.xml

# jar file bundled dependencies 
java -cp  $TARGETPATH/demo-1.0-SNAPSHOT.jar htron.App 

